name: arch_gen
description: This is a Dart CLI tool that automatically generates files for the Data layer in a Clean Architecture structure.
version: 0.1.0
homepage: https://github.com/okstring/arch_gen
repository: https://github.com/okstring/arch_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  archgen: archgen